### ISSUE TITLE
Gesamtdauer anzeigen

### ISSUE THREAD

**Issue by lizzard77** [lizzard77/fvtt-tick-combat#2]
Manchmal wäre es gut, die Gesamtdauer des Kampfes sehen zu können. Am linken Rand der Timeline sollte es eine Box geben, die anzeigt, wie lange der Kampf schon läuft. Hierfür könnten die Ticks aufsummiert werden, die abezogen werden, nachdem im Combat Tracker der Kampf als gestartet markiert wird. Vorher ist unsinnig, da ja bereits beim ersten Einrichten Ticks abgezogen werden, um einen Charakter auf 0 zu bringen.

**Comment by Tschuangtse** [comment]
Das würde gut zu der Idee passen, dass man statt einem Clear-All Button einfach die Start Combat und Stop Combat Funktion von Foundry über die Timeline selbst aufrufbar macht. Ich versuche halt von der Standard-Combat-Seite weg zu kommen, so gut ich kann.

**Comment by lizzard77** [comment]
![image](https://github.com/lizzard77/fvtt-tick-combat/assets/15921685/6207a1bf-a9fa-49d8-a40a-0965e231d4bb)

**Comment by Tschuangtse** [comment]
Ich nehme an, dass es hier eine ungewollte Interaktion zwischen der neuen Lösung zum Starten des Kampfes und dem Zähler gibt.
Wenn ich Werte eintrage wird natürlich auf 0 runtergerechnet. Diese Ticks werden bereits zur totalen Dauer gezählt, obwohl ja nur die initiale Einordnung passiert ist.

**Comment by lizzard77** [comment]
Die Timeline "weiß" nicht, wann die initiale Einordnung fertig ist. Vorschlag - der Kampf könnte in der Timeline mit einem extra Button gestartet werden, so dass diese initiale Phase von der Bedienung her komplett abgetrennt ist.

**Comment by Tschuangtse** [comment]
In dem Fall wäre der aktuelle Start bei Kämpfer mit INI größer 0 natürlich nicht mehr nötig. 
Es ist eine passable Lösung. Die Alternative wäre, dass ein Bool _countTotalTicks = false gesetzt wird, welcher abgefragt wird, wenn das Programm runterrechnen will. Der Bool wird dann nach dem ersten runterrechnen auf true gesetzt und dann immer abgefragt, ehe die Ticks gezählt werden. Persönlich fände ich das schöner, aber beide Lösungen funktionieren für mich und ich würde dir die Wahl überlassen, was einfacher ist.
