### ISSUE TITLE
Token-Bewegung löscht Änderungen des GM

### ISSUE THREAD

**Issue by lizzard77** [lizzard77/fvtt-tick-combat#5]
Derzeit ist es so, dass wenn ein Token bewegt wird, während ich eine Änderung in der Timeline mache, dass meine Änderung verworfen wird und die Timeline den Fokus verliert

**Comment by lizzard77** [comment]
Info dazu:

Also, hier mal zwei Clips.

Im ersten siehst du, dass meine Eingabe für den Kämpfer Charim gelöscht wird, wenn ich das Token bewege. Sein Tick Wert ändert sich dann nicht.

https://github.com/lizzard77/fvtt-tick-combat/assets/15921685/98c2c997-f896-4d59-a243-c3f35db39b84

Im zweiten siehst du zuerst, dass ich während einer laufenden Bewegung das Problem nicht habe. Interessanter Weise ist es hier so, dass beim neu Anwählen des Tokens wieder der Tick-Wert aus meiner Eingabe gelöscht wird, diesmal aber aufaddiert wird. Das ist also nicht konsistent.

https://github.com/lizzard77/fvtt-tick-combat/assets/15921685/6a4b5318-8acb-4ac7-8a3c-4ef327a7d636

Den dritten Fall kann ich erst mit Video machen, wenn ich einen Spieler ausgegraben habe, aber effektiv ist es der erste Fall. Ich bereite eine Eingabe vor, der Spieler wählt den Token, und meine Eingabe wird verworfen. Nur, dass es nicht direkt bei Auswahl durch den Spieler passiert, sondern erst, wenn ich versuche die Änderung zu übernehmen.

**Comment by Tschuangtse** [comment]
Hier gibt es einen kleinen Schönheitsfehler: wenn ich eine Eingabe bestätige per Enter, wie besprochen, werden auch alle anderen Eingaben gelöscht.
Das ist in der Realität nicht wirklich ein Fall, der eintreten sollte, da ich die Ticks logischerweise sequentiel eingebe, ist aber aufgefallen. Quasi mehr was für die Doku als alles andere.
