### ISSUE TITLE
Esc-Taste schließt Timeline

### ISSUE THREAD

**Issue by lizzard77** [lizzard77/fvtt-tick-combat#6]
Die Timeline nimmt sich derzeit immer automatisch den Fokus. Wenn ich ein Token abwählen will per ESC, wird zuerst die Timeline geschlossen. Bei einem zweiten mal ESC wird erst das Token abgewählt. Danach muss ich die Timeline über den Combat Tracker wieder öffnen. Idealerweise ignoriert die Timeline das ESC und nimmt sich nicht automatisch den Fokus.

**Comment by Tschuangtse** [comment]
Die ESC-Taste schließt zwar die Timeline nicht mehr, aber gleichzeitig kann ich Token auch nicht mehr per ESC abwählen.
Wenn ich also ein Token auswähle, welches einem Spieler gehört und das Token nicht alles sieht, kann ich teils andere Tokens nicht mehr auswählen. Meine eigene Sicht wird reduziert und ich kann es nicht mehr abwählen.

**Comment by lizzard77** [comment]
Das eine hängt intern wohl am Anderen. Vorschlag: wenn das Timeline-Fenster sein eigenes Schließen verhindert, deselektieren wir stattdessen automatisch alle Actors?

**Comment by Tschuangtse** [comment]
Nachdem ich jetzt etwas drüber nachgedacht habe, glaube ich, dass eine technische Lösung hier zu finden mehr Aufwand ist, als meine Spieler dazu zu zwingen, mit Shift-Klick zu deselektieren. Für mich selbst funktioniert das gut genug.
Außerdem habe ich nie getestet, ob die Time Line bei ihnen zugeht, wenn sie ESC drücken.
--> Ich würde den Punkt einfach fallen lassen (Aus der Kategorie: gut genug)
