### ISSUE TITLE
Leeren-Funktion

### ISSUE THREAD

**Issue by lizzard77** [lizzard77/fvtt-tick-combat#7]
Ich benötige noch einen Clear all Button, welchen Spieler nicht sehen. Der Button soll alle aktiven Events löschen und alle Token auf der gegenwärtigen Szene aus dem Combat State ziehen.

**Comment by lizzard77** [comment]
Anmerkung: beim Beenden des Combat über Foundry soll automatisch geleert werden

**Comment by Tschuangtse** [comment]
Das funktioniert auch, nur der Mensch dahinter nicht. Ich vergesse regelmäßig, irgendwas mit dem normalen Combat Tracker zu machen. Letztlich ist das eines der kleinsten QoL überhaupt, da ich ja jederzeit in den Combat Tracker hüpfen kann und auch nachträglich den Kampf starten und beenden kann.

Vllt. wäre eine Implementierung am sinnvollsten, wo Start und Stop Combat in der Timeline mit den Ticks verlinkt wären?
Also sprich, dass die Funktion hinter Start und Stop Combat je über das Tool selbst aufgerufen wird.

**Comment by lizzard77** [comment]
Idee/Test: Combat startet automagisch, wenn > 0 Teilnehmer im Combat sind (aktiviert über das Token-HUD). Combat endet automatisch (nach Rückfrage), wenn der GM die Timeline schließt.
